theme: jekyll-theme-minimal
title: Ampmie's Homepage
description: Hi, My name is Ampmie. This space is a collection of my digital tools. 
I help individuals and businesses make smarter financial and digital decisions. 
Bookmark this to keep an eye on my updates!
